name: Test site code
on:
  workflow_dispatch:
  push:
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true
jobs:
  test:
    name: Test site code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Prettier
        run: yarn format
      - name: Lint
        run: yarn lint
      - name: Typecheck
        run: yarn typecheck
      - name: Gatsby build
        run: yarn build
